---
title: "STATS 786 Group Project"
author: "Yucheng Wang, Eric Shi, Tongxin Li, Jinze, Li"
date: "2024-05-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(fpp3)
library(tsibbledata)
Sys.setlocale("LC_TIME", "English_United States.1252")
```

# 1. Exploratory data analysis
```{r, warning=FALSE}
# 读取数据
data = read_csv("qgdp_training.csv")
# 选择第一列和第十七列
data = data %>% select(1, 17)
# 确保第一列是日期格式
data = data %>%
  mutate(Date = yearquarter(Date))
# 将数据转换为tsibble对象
ts_data = data %>%
  as_tsibble(index = Date)

ts_data <- ts_data %>%
  rename(Wholesale = `Wholesale Trade`)  # 列名调整
ts_data %>% 
  autoplot()
# 进行STL分解并画图
ts_data %>%
  model(stl = STL(Wholesale, robust = TRUE)) %>%
  components() %>%
  autoplot()
```

# 2. ETS models
```{r}

```


# 3. ARIMA models
```{r}

```

# 4. Neural network autoregression (NNAR) models
```{r, warning=FALSE}
data_Agriculture <- train %>% 
  select(Date, Agriculture)

fit <- data_Agriculture %>% 
  model(NNETAR(Agriculture))

data_Agriculture %>% 
  autoplot(Agriculture, color = 'purple', alpha = 0.5) +
  geom_line(aes(y = augment(fit)$.fitted))

accuracy(fit)
```

# 5. Assumption checking
```{r}

```

# 6. Forecasting
```{r}

```

# 7. Member contributions






